version: "3.7"
services:
  api-plant:
    depends_on: 
      - postgresql
    build: .
    ports:
      - "8080:8080"
    environment:
      API_PLANT_DSN: postgres://postgres:postgres@postgresql/metron

  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: metron
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
