version: "3.7"
services:
  test:
    image: golang:1.18
    working_dir: /app
    volumes:
      - .:/app
    depends_on: 
      - postgresql
    build: .
    ports:
      - "8080:8080"
    environment:
      API_PLANT_DSN: postgres://postgres:postgres@postgresql/metron
    entrypoint: go test /app/internal/plants

  postgresql:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: metron
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

